CREATE SEQUENCE numReference 
Start WITH 0 
INCREMENT by 1;

CREATE SEQUENCE numCommande
Start WITH 0 
INCREMENT by 1;

CREATE SEQUENCE codeZebre
Start WITH 0 
INCREMENT by 1;

CREATE SEQUENCE codeIndividu
Start WITH 0 
INCREMENT by 1;

CREATE SEQUENCE numLivraisons 
Start WITH 0 
INCREMENT by 1;

CREATE SEQUENCE numPaiement
START WITH 0
INCREMENT BY 1;
