CREATE SEQUENCE numModification 
Start WITH 1 
INCREMENT by 1;

CREATE SEQUENCE numReference 
Start WITH 1 
INCREMENT by 1;

CREATE SEQUENCE numCommande
Start WITH 1 
INCREMENT by 1;

CREATE SEQUENCE numFacture
Start WITH 1 
INCREMENT by 1;

CREATE SEQUENCE codeZebre
Start WITH 1 
INCREMENT by 1;

CREATE SEQUENCE codeFournisseur 
Start WITH 1 
INCREMENT by 1;

CREATE SEQUENCE codeIndividu
Start WITH 1 
INCREMENT by 1;

CREATE SEQUENCE codeClient
Start WITH 1 
INCREMENT by 1;