DROP SEQUENCE CODECLIENT;
DROP SEQUENCE CODEFOURNISSEUR;
DROP SEQUENCE CODEINDIVIDU;
DROP SEQUENCE CODEZEBRE;
DROP SEQUENCE NUMCOMMANDE;
DROP SEQUENCE NUMFACTURE;
DROP SEQUENCE NUMMODIFICATION;
DROP SEQUENCE NUMREFERENCE;
